### ISSUE TITLE
Can not run container with nginx-proxy

### ISSUE THREAD

**Issue by aleksander351** [bitnami/bitnami-docker-phpbb#51]
**Description**

I am using nginx-proxy reverse proxy docker container to serve multiple containers on the same host machine.

But I am unable to get it to work with this image.

Has anybody tried it?

Version information coming soon...

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

Could you provide a docker-compose file that reproduces the issue?

**Comment by aleksander351** [comment]
`version: '3'
    services:
    
      mariadb:
        user: root
        image: 'bitnami/mariadb:latest'
        environment:
          - MARIADB_DATABASE=somedatabase
          - MARIADB_USER=root
          - MARIADB_PASSWORD=somepassword
          - MARIADB_ROOT_USER=root
          - MARIADB_ROOT_PASSWORD=somepassword
        volumes:
          - /var/lib/docker/volumes/mariadb_some:/bitnami
        ports:
          - '3306:3306'
        container_name: mariadb_phpbb
    
      phpbb:
        image: 'bitnami/phpbb:3'
        labels:
          kompose.service.type: nodeport
        environment:
          - MARIADB_HOST=mariadb
          - MARIADB_PORT_NUMBER=3306
          - PHPBB_DATABASE_NAME=somedatabase
          - PHPBB_DATABASE_USER=root
          - PHPBB_DATABASE_PASSWORD=somepassword
          - PS_DOMAIN=myproxy.domain.com
          - VIRTUAL_HOST=myproxy.domain.com
          - LETSENCRYPT_HOST=myproxy.domain.com
          - LETSENCRYPT_EMAIL=myemail@gmail.com
        ports:
          - "8089:80"
        volumes:
          - /var/lib/docker/volumes/some_phpbb:/bitnami
        container_name: some_phpbb

    networks:
      default:
        external:
          name: some_network`

I noticed, that the volumes must be empty on startup, or it will not even start.

A custom network should connect the two containers. Also tried with depends_on and -links.

The farthest I came is:
mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful

I also need to add, I am running some other mariadb containers with different names and I am not sure if that is a problem.

**Comment by javsalgar** [comment]
As the original question was if phpbb worked with nginx-proxy, I used this configuration and it worked without issues.

```
version: '3'
services:

  mariadb:
    user: root
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_DATABASE=somedatabase
      - MARIADB_USER=user
      - MARIADB_PASSWORD=somepassword
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=somepassword
    volumes:
      - /var/lib/docker/volumes/mariadb_some:/bitnami
    ports:
      - '3306:3306'
    container_name: mariadb_phpbb

  phpbb:
    image: 'bitnami/phpbb:3'
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PHPBB_DATABASE_NAME=somedatabase
      - PHPBB_DATABASE_USER=root
      - PHPBB_DATABASE_PASSWORD=somepassword
      - PS_DOMAIN=myproxy.domain.com
      - VIRTUAL_HOST=myproxy.domain.com
      - LETSENCRYPT_HOST=myproxy.domain.com
      - LETSENCRYPT_EMAIL=myemail@gmail.com
    ports:
      - "8089:80"
    volumes:
      - /var/lib/docker/volumes/some_phpbb:/bitnami
    container_name: some_phpbb

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
```

Note that you cannot use root for MARIADB_USER in the mariadb container, as it is meant to be used for a different user than `root`.

![image](https://user-images.githubusercontent.com/1133777/47139832-0fc4ae80-d2bd-11e8-92df-38b89da0185a.png)

**Comment by aleksander351** [comment]
Still no luck. 

The verbose error is a bit more descriptive.

`
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.36-MariaDB) starting as process 1 ...
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] mysqld: File '/bitnami/mariadb/data/aria_log_control' not found (Errcode: 13 "Permission denied")
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/bitnami/mariadb/data/aria_log_control'
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] Plugin 'Aria' init function returned error.
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
mariadb_phpbb              |
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: Using Linux native AIO
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: Using SSE crc32 instructions
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] InnoDB: Completed initialization of buffer pool
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] InnoDB: ./ibdata1 can't be opened in read-write mode
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] InnoDB: The system tablespace must be writable!
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_phpbb              | 2018-10-18 18:36:57 140581904391104 [ERROR] Aborting
`

**Comment by javsalgar** [comment]
Did you try with my docker-compose and removed the volumes first?

**Comment by aleksander351** [comment]
Yes, I tried with that settings with all volume files deleted. Although you have
     `- PHPBB_DATABASE_USER=root` 
I tried that and later also changed that to 
    `- PHPBB_DATABASE_USER=user` 

It still says:
    `some_phpbb | mysql-c ERROR [canConnect] Connection with 'user' user is unsuccessful
    some_phpbb | Error executing 'postInstallation': Cannot connect to MySQL server:
    some_phpbb | MySQL command failed to run. Error:
    some_phpbb |  ERROR 1045 (28000): Access denied for user 'user'@'172.18.0.21' (using password: YES)
    `

I find it strange that after the command `docker-compose rm -v`, the volumes on my host do not get deleted. I delete them manually inside /var/lib/docker/volumes

I also need to bind to my external network, which the nginx-proxy uses. Which is not specified in your compose file.

**Comment by javsalgar** [comment]
For removing the volumes I use `docker-compose down -v`, could you try that?

**Comment by aleksander351** [comment]
Ok, so I did not specify any volumes. But still the same:
Does not matter what I put in the PHPBB_DATABASE_USER variable, still the same...
    `
    some_phpbb | mysql-c INFO  Found MySQL server listening at mariadb:3306
    some_phpbb | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
    some_phpbb | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
    some_phpbb | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
    some_phpbb | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
    some_phpbb | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
    some_phpbb | Error executing 'postInstallation': Cannot connect to MySQL server:
    some_phpbb | MySQL command failed to run. Error:
    some_phpbb |  ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.21' (using password: YES)
    `

Could it be, that it is shomehow creating the container twice? Notice the duplicate creating lines:
     `
     Creating forumphpbb6_mariadb1_1 ... done
     Creating forumphpbb6_mariadb1_1 ...
     Creating forumphpbb6_phpbb_1    ... done
     `
Also tried changing the service name of mariadb to mariadb1, if it possibly conflicts with another mariadb container...

**Comment by aleksander351** [comment]
I went inside the mariadb container and tried to connect to mysql:

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2 "No such file or directory")`

The mysql.sock file does not exist in tmp directory

**Comment by aleksander351** [comment]
Some more error messages when trying to run mysqld inside container:

$ run ./run.sh
     `2018-10-22 21:17:21 140012877867968 [ERROR] InnoDB: ./ibdata1 can't be opened in read-write 
     mode
     2018-10-22 21:17:21 140012877867968 [ERROR] InnoDB: The system tablespace must be writable!
     2018-10-22 21:17:21 140012877867968 [ERROR] Plugin 'InnoDB' init function returned error.
     2018-10-22 21:17:21 140012877867968 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE 
     failed.
     2018-10-22 21:17:21 140012877867968 [Note] Plugin 'FEEDBACK' is disabled.
     2018-10-22 21:17:21 140012877867968 [ERROR] Could not open mysql.plugin table. Some plugins 
     may be not loaded
     2018-10-22 21:17:21 140012877867968 [ERROR] Unknown/unsupported storage engine: InnoDB
     2018-10-22 21:17:21 140012877867968 [ERROR] Aborting`

$ /opt/bitnami/mariadb/sbin/mysqld --user=root
     `2018-10-22 21:20:47 140417126755264 [ERROR] Could not open mysql.plugin table. Some plugins 
     may be not loaded
     2018-10-22 21:20:47 140417126755264 [ERROR] Can't open and lock privilege tables: Table 
     'mysql.servers' doesn't exist
     2018-10-22 21:20:47 140417126755264 [Note] Server socket created on IP: '0.0.0.0'.
     2018-10-22 21:20:47 140417126755264 [ERROR] Fatal error: Can't open and lock privilege tables: 
     Table 'mysql.user' doesn't exist`

**Comment by javsalgar** [comment]
This is really strange. Please share with me the exact docker compose you are testing (and has the volumes disabled)

**Comment by aleksander351** [comment]
`
     version: '3'
     services:

       mariadb1:
         user: root
         image: bitnami/mariadb:latest
         environment:
           - MARIADB_DATABASE=bitnami_phpbb
           - MARIADB_USER=bn_phpbb
           - MARIADB_PASSWORD=somepassword
           - MARIADB_ROOT_PASSWORD=rootpassword
         ports:
           - "3310:3306"
         container_name: mariadb_phpbb

       phpbb:
         image: bitnami/phpbb:3
         labels:
           kompose.service.type: nodeport
         environment:
           - PHPBB_USERNAME=admin
           - PHPBB_PASSWORD=somepass
           - PHPBB_FIRST_NAME=admin
           - PHPBB_LAST_NAME=last
           - PHPBB_FORUM_NAME="Some forum"
           - PHPBB_FORUM_DESCRIPTION="Some topic"
           - PHPBB_EMAIL=some.email@gmail.com
           - PHPBB_HOST=some.email@gmail.com
           - PHPBB_DATABASE_USER=bn_phpbb
           - PHPBB_DATABASE_PASSWORD=somepassword
           - PS_DOMAIN=subdomain.domain.net
           - VIRTUAL_HOST=subdomain.domain.net
           - LETSENCRYPT_HOST=subdomain.domain.net
           - LETSENCRYPT_EMAIL=some.email@gmail.com
         ports:
           - "8089:80"
         links:
           - mariadb1:mariadb1
         container_name: some_phpbb

     networks:
       default:
         external:
           name: network1

     `

The nginx-proxy and letsencrypt containares are mounted separately on the same network.

**Comment by javsalgar** [comment]
To make it work in my system, I did the following:

- Remove the `user: root` from MariaDB, as it is a non-root container
- As the mariadb container has a hostname different from `mariadb`, then you need to set the `MARIADB_HOST` env var.

```
 version: '3'
 services:

   mariadb1:
     user: root
     image: bitnami/mariadb:latest
     environment:
       - MARIADB_DATABASE=bitnami_phpbb
       - MARIADB_USER=bn_phpbb
       - MARIADB_PASSWORD=somepassword
       - MARIADB_ROOT_PASSWORD=rootpassword
     ports:
       - "3310:3306"
     container_name: mariadb_phpbb

   phpbb:
     image: bitnami/phpbb:3
     labels:
       kompose.service.type: nodeport
     environment:
       - PHPBB_USERNAME=admin
       - PHPBB_PASSWORD=somepass
       - PHPBB_FIRST_NAME=admin
       - PHPBB_LAST_NAME=last
       - PHPBB_FORUM_NAME="Some forum"
       - PHPBB_FORUM_DESCRIPTION="Some topic"
       - PHPBB_EMAIL=some.email@gmail.com
       - PHPBB_HOST=some.email@gmail.com
       - PHPBB_DATABASE_USER=bn_phpbb
       - PHPBB_DATABASE_PASSWORD=somepassword
       - PS_DOMAIN=subdomain.domain.net
       - VIRTUAL_HOST=subdomain.domain.net
       - LETSENCRYPT_HOST=subdomain.domain.net
       - LETSENCRYPT_EMAIL=some.email@gmail.com
       - MARIADB_HOST=mariadb_phpbb
     ports:
       - "8089:80"
     links:
       - mariadb1:mariadb1
     container_name: some_phpbb
```

Also, just in case, remove the `bitnami/mariadb` image so it gets pulled again.
