### ISSUE TITLE
Phpbb failing to initialise MySQL tables

### ISSUE THREAD

**Issue by ADRFranklin** [bitnami/bitnami-docker-phpbb#57]
**Description**

Phpbb is not creating the tables after initialising and connecting to the MySQL server, and instead shows an error. It doesn't seem to matter if I set the volumes to be local or persistent, it continues to not create tables 

**Describe the results you received:**

This is the process that happens, even though it says it connected correctly
```
phpbb_1_49eb50b53610 | nami    INFO  Initializing libphp
phpbb_1_49eb50b53610 | nami    INFO  libphp successfully initialized
phpbb_1_49eb50b53610 | nami    INFO  Initializing phpbb
phpbb_1_49eb50b53610 | mysql-c INFO  Trying to connect to MySQL server
phpbb_1_49eb50b53610 | mysql-c INFO  Found MySQL server listening at mariadb:3306
phpbb_1_49eb50b53610 | mysql-c INFO  MySQL server listening and working at mariadb:3306
phpbb_1_49eb50b53610 | phpbb   INFO  Configuring the application. Please be patient, it can take several minutes to finish.
phpbb_1_49eb50b53610 | phpbb   INFO  Installation completed
phpbb_1_49eb50b53610 | Error executing 'postInstallation': MySQL command failed to run. Error:
phpbb_1_49eb50b53610 |  ERROR 1146 (42S02) at line 1: Table 'gtcnr_forum.phpbb_config' doesn't exist
```

**Describe the results you expected:**

I expected it to create the tables in the database, like my other installation of phpbb which is the exact same configuration as this.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
version: '3'
services:
  mariadb:
    env_file: config.env
    image: 'bitnami/mariadb:latest'
    ports:
      - "3307:3306"
    volumes:
      - 'mariadb_data:/bitnami'

  phpbb:
    env_file: config.env
    image: 'bitnami/phpbb:3'
    volumes:
      - 'phpbb_data:/bitnami'
    depends_on:
      - mariadb
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:forum.xxx.gs"
      - "traefik.port=443"
      - "traefik.protocol=https"

networks:
  proxy:
    external: true

volumes:
  mariadb_data:
    driver: local

  phpbb_data:
    driver: local
```

environment variables

```
# MariaDB #
MARIADB_HOST=mariadb
MARIADB_PORT_NUMBER=3306
MARIADB_ROOT_USER=some_user
MARIADB_ROOT_PASSWORD=some_pass
MARIADB_DATABASE=some_db
ALLOW_EMPTY_PASSWORD=no

# PHPBB #
PHPBB_USERNAME=my_user
PHPBB_PASSWORD=my_pass
PHPBB_FIRST_NAME=my_name
PHPBB_LAST_NAME=my_last_name
PHPBB_FORUM_NAME=name_of_site
PHPBB_FORUM_DESCRIPTION="Welcome to name_of_site"
PHPBB_EMAIL=xxx@xxx.gs
PHPBB_DATABASE_NAME=some_db
PHPBB_DATABASE_USER=some_user
PHPBB_DATABASE_PASSWORD=some_pass
```

**Version**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 19
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 100
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-143-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.611GiB
Name: vps608685
ID: 6O3F:6VIN:WJFG:G7BD:N6IG:QRZH:RNYZ:V4ZI:5XSE:OVVU:JH5C:TVAW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Dedicated Server (Linux, Ubuntu 16.04)

**Comment by alemorcuq** [comment]
Hi @ADRFranklin,

I see you are loading your environment variables through a `.env` file. Does your `.env` file contain any quotation marks? Note that `docker-compose` [treats quotation marks as part of the value](https://docs.docker.com/compose/env-file/), so you don't have to quote values that contain spaces. For example, `PHPBB_FORUM_DESCRIPTION=Welcome to name_of_site` is a valid line for your `.env` file.

**Comment by ADRFranklin** [comment]
Hi @alemorcuq,

I am aware of this, however with and without quotation marks, there seems to be no difference in how phpbb sets up the database. It still continues to fails to populate the database with any tables.

I'm not sure of what causes this, but I still can not get this to work.

**Comment by alemorcuq** [comment]
I've been able to reproduce your issue using this `docker-compose.yml`:

```
version: '3'
services:
  mariadb:
    env_file: config.env
    image: 'bitnami/mariadb:latest'
    ports:
      - "3307:3306"
    volumes:
      - 'mariadb_data:/bitnami'

  phpbb:
    env_file: config.env
    image: 'bitnami/phpbb:3'
    volumes:
      - 'phpbb_data:/bitnami'
    depends_on:
      - mariadb
    networks:
      - proxy
      - default
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:forum.xxx.gs"
      - "traefik.port=443"
      - "traefik.protocol=https"

networks:
  proxy:
    external: true

volumes:
  mariadb_data:
    driver: local

  phpbb_data:
    driver: local
```
And this `config.env`:
```
# MariaDB #
MARIADB_HOST=mariadb
MARIADB_PORT_NUMBER=3306
MARIADB_ROOT_USER=some_user
MARIADB_ROOT_PASSWORD=some_pass
MARIADB_DATABASE=some_db
ALLOW_EMPTY_PASSWORD=no

# PHPBB #
PHPBB_USERNAME=my_user
PHPBB_PASSWORD=my_pass
PHPBB_FIRST_NAME=my_name
PHPBB_LAST_NAME=my_last_name
PHPBB_FORUM_NAME=name_of_site
PHPBB_FORUM_DESCRIPTION="Welcome to name_of_site"
PHPBB_EMAIL=xxx@xxx.gs
PHPBB_DATABASE_NAME=some_db
PHPBB_DATABASE_USER=some_user
PHPBB_DATABASE_PASSWORD=some_pass
```
Bringing it up with `docker-compose up` yields:
```
phpbb_1    | nami    INFO  Initializing phpbb
phpbb_1    | mysql-c INFO  Trying to connect to MySQL server
phpbb_1    | mysql-c INFO  Found MySQL server listening at mariadb:3306
phpbb_1    | mysql-c INFO  MySQL server listening and working at mariadb:3306
phpbb_1    | phpbb   DEBUG Preparing webserver environment...
phpbb_1    | phpbb   DEBUG Configuring PHP settings...
phpbb_1    | phpbb   DEBUG Configuring phpBB...
phpbb_1    | phpbb   DEBUG Installing phpBB...
phpbb_1    | phpbb   INFO  Configuring the application. Please be patient, it can take several minutes to finish.
phpbb_1    | phpbb   INFO  Installation completed
phpbb_1    | Error executing 'postInstallation': MySQL command failed to run. Error:
phpbb_1    |  ERROR 1146 (42S02) at line 1: Table 'some_db.phpbb_config' doesn't exist
phpbb_1    |
test2_phpbb_1 exited with code 1
```

However, using this `config.env`, without any quotes:
```
# MariaDB #
MARIADB_HOST=mariadb
MARIADB_PORT_NUMBER=3306
MARIADB_ROOT_USER=some_user
MARIADB_ROOT_PASSWORD=some_pass
MARIADB_DATABASE=some_db
ALLOW_EMPTY_PASSWORD=no

# PHPBB #
PHPBB_USERNAME=my_user
PHPBB_PASSWORD=my_pass
PHPBB_FIRST_NAME=my_name
PHPBB_LAST_NAME=my_last_name
PHPBB_FORUM_NAME=name_of_site
PHPBB_FORUM_DESCRIPTION=Welcome to name_of_site
PHPBB_EMAIL=xxx@xxx.gs
PHPBB_DATABASE_NAME=some_db
PHPBB_DATABASE_USER=some_user
PHPBB_DATABASE_PASSWORD=some_pass
```
And running:
```
$ docker-compose down -v
$ docker-compose up
```
It works:

```
phpbb_1    | nami    INFO  Initializing phpbb
phpbb_1    | mysql-c INFO  Trying to connect to MySQL server
phpbb_1    | mysql-c INFO  Found MySQL server listening at mariadb:3306
phpbb_1    | mysql-c INFO  MySQL server listening and working at mariadb:3306
phpbb_1    | phpbb   INFO  Configuring the application. Please be patient, it can take several minutes to finish.
phpbb_1    | phpbb   INFO  Installation completed
phpbb_1    | phpbb   INFO
phpbb_1    | phpbb   INFO  ########################################################################
phpbb_1    | phpbb   INFO   Installation parameters for phpbb:
phpbb_1    | phpbb   INFO     Username: my_user
phpbb_1    | phpbb   INFO     Password: **********
phpbb_1    | phpbb   INFO     Email: xxx@xxx.gs
phpbb_1    | phpbb   INFO     First Name: my_name
phpbb_1    | phpbb   INFO     Last Name: my_last_name
phpbb_1    | phpbb   INFO     Forum Name: name_of_site
phpbb_1    | phpbb   INFO   (Passwords are not shown for security reasons)
phpbb_1    | phpbb   INFO  ########################################################################
phpbb_1    | phpbb   INFO
phpbb_1    | nami    INFO  phpbb successfully initialized
phpbb_1    | INFO  ==> Starting phpbb...
phpbb_1    | 127.0.0.1 - - [02/Apr/2019:16:00:54 +0000] "POST /install/app.php/install HTTP/1.1" 200 276605
```

Could you please double check you are not using any quotes? Quotes may prevent the installer to configure phpBB and create the tables. Also check you don't have any persisted data that could be preventing the initialization.
