### ISSUE TITLE
Feature request: favicon.ico symlink

### ISSUE THREAD

**Issue by RafaelMiquelino** [bitnami/bitnami-docker-phpbb#64]
Hi, could you please include a favicon.ico symlink to the `/bitnami/phpbb/` directory on your next release? This would help a lot including a favicon for the board.

Thanks,
Rafael

**Comment by joancafom** [comment]
Hi @RafaelMiquelino ,

Thanks for your idea, we value it so much in order to constantly improve our releases 😀. I might be wrong, but it sound like you are trying to set up an easy way of mounting an individual file to the container (in this case, the favicon). Am I right? In that case, you could use mount that single `favicon.ico` as a volume:

```yml
 phpbb:
    image: 'docker.io/bitnami/phpbb:3-debian-10'
    ...
    volumes:
      - 'phpbb_data:/bitnami'
      - './favicon.ico:/bitnami/phpbb/favicon.ico'
    ...
```

Could that work for your?  
Glad to help, thanks!
